# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/bd/design_1/ip/design_1_ram_dp0_256x8_0_1/design_1_ram_dp0_256x8_0_1.xci
# IP: The module: 'design_1_ram_dp0_256x8_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/ip/ram0/ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/bd/design_1/ip/design_1_ram_dp0_256x8_0_1/design_1_ram_dp0_256x8_0_1.xci
# IP: The module: 'design_1_ram_dp0_256x8_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/ip/ram0/ram0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram0 || ORIG_REF_NAME==ram0} -quiet] -quiet
