# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UIR_0_0/design_1_UIR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_UIR_0_0 || ORIG_REF_NAME==design_1_UIR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74LS161_0_1/design_1_m74LS161_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74LS161_0_1 || ORIG_REF_NAME==design_1_m74LS161_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m74LS161_1_0/design_1_m74LS161_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m74LS161_1_0 || ORIG_REF_NAME==design_1_m74LS161_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_addr_adpt_0_0/design_1_addr_adpt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_addr_adpt_0_0 || ORIG_REF_NAME==design_1_addr_adpt_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_shifter_0_1/design_1_shifter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_shifter_0_1 || ORIG_REF_NAME==design_1_shifter_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff4_0_0/design_1_dff4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff4_0_0 || ORIG_REF_NAME==design_1_dff4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff4_1_0/design_1_dff4_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff4_1_0 || ORIG_REF_NAME==design_1_dff4_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dff4_2_0/design_1_dff4_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dff4_2_0 || ORIG_REF_NAME==design_1_dff4_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_0_0/design_1_and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_0_0 || ORIG_REF_NAME==design_1_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_1_0/design_1_and2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_1_0 || ORIG_REF_NAME==design_1_and2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_and2_2_0/design_1_and2_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_and2_2_0 || ORIG_REF_NAME==design_1_and2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder4_0_3/design_1_adder4_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adder4_0_3 || ORIG_REF_NAME==design_1_adder4_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rom1_256x24_0_2/design_1_rom1_256x24_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rom1_256x24_0_2 || ORIG_REF_NAME==design_1_rom1_256x24_0_2} -quiet] -quiet

# IP: ip/rom1/rom1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1} -quiet] -quiet

# XDC: d:/coding/computer_organization/exp/exp14/exp14.gen/sources_1/bd/design_1/design_1_ooc.xdc
