# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cg_fpga_0_0/design_1_cg_fpga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cg_fpga_0_0 || ORIG_REF_NAME==design_1_cg_fpga_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_in_0_0/design_1_adpt_in_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_in_0_0 || ORIG_REF_NAME==design_1_adpt_in_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_dp1_1Kx4_0_2/design_1_ram_dp1_1Kx4_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ram_dp1_1Kx4_0_2 || ORIG_REF_NAME==design_1_ram_dp1_1Kx4_0_2} -quiet] -quiet

# IP: ip/ram1/ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_dp1_1Kx4_1_2/design_1_ram_dp1_1Kx4_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ram_dp1_1Kx4_1_2 || ORIG_REF_NAME==design_1_ram_dp1_1Kx4_1_2} -quiet] -quiet

# IP: ip/ram1/ram1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adpt_out_0_0/design_1_adpt_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adpt_out_0_0 || ORIG_REF_NAME==design_1_adpt_out_0_0} -quiet] -quiet

# XDC: d:/coding/computer_organization/exp/exp12_1/exp12_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
