# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/coding/computer_organization/exp/exp12_1/exp12_1.srcs/sources_1/bd/design_1/ip/design_1_ram_dp1_1Kx4_0_2/design_1_ram_dp1_1Kx4_0_2.xci
# IP: The module: 'design_1_ram_dp1_1Kx4_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/coding/computer_organization/exp/exp12_1/exp12_1.srcs/sources_1/ip/ram1/ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet

# IP: D:/coding/computer_organization/exp/exp12_1/exp12_1.srcs/sources_1/bd/design_1/ip/design_1_ram_dp1_1Kx4_0_2/design_1_ram_dp1_1Kx4_0_2.xci
# IP: The module: 'design_1_ram_dp1_1Kx4_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/coding/computer_organization/exp/exp12_1/exp12_1.srcs/sources_1/ip/ram1/ram1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram1 || ORIG_REF_NAME==ram1} -quiet] -quiet
