# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/ip/ram0/ram0.xci
# IP: The module: 'ram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/computer_organization/exp/exp11/exp11.gen/sources_1/ip/ram0/ram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/coding/computer_organization/exp/exp11/exp11.srcs/sources_1/ip/ram0/ram0.xci
# IP: The module: 'ram0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/coding/computer_organization/exp/exp11/exp11.gen/sources_1/ip/ram0/ram0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
